import { router, useLocalSearchParams } from "expo-router";
import { useEffect, useMemo, useState } from "react";
import { Alert, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { AppBackground } from "../components/AppBackground";
import { BackIconButton } from "../components/BackIconButton";
import { PrimaryButton } from "../components/PrimaryButton";
import { appVariant } from "../lib/app-variant";
import { t } from "../lib/i18n";
import { readAppState } from "../lib/storage";
import { getLocalizedSubjects } from "../lib/subjects";
import { palette, shadows } from "../lib/theme";
import { generateLearningLesson } from "../services/ai";
import type { AppLanguage, LearningLesson, UserProfile } from "../types/app";

const OTHER = "other";

export default function LearningHubScreen() {
  const params = useLocalSearchParams<{
    subjectId?: string;
    subjectName?: string;
    topicName?: string;
    grade?: string;
    context?: string;
  }>();
  const [profile, setProfile] = useState<UserProfile | null>(null);
  const [language, setLanguage] = useState<AppLanguage>("en");
  const subjects = useMemo(() => getLocalizedSubjects(language), [language]);
  const initialSubjectId =
    typeof params.subjectId === "string" && subjects.some((entry) => entry.id === params.subjectId)
      ? params.subjectId
      : typeof params.subjectName === "string"
        ? OTHER
        : subjects[0]?.id ?? OTHER;
  const [subjectId, setSubjectId] = useState(initialSubjectId);
  const [customSubject, setCustomSubject] = useState(typeof params.subjectName === "string" ? params.subjectName : "");
  const selectedSubject = subjects.find((entry) => entry.id === subjectId) ?? null;
  const [topicId, setTopicId] = useState(OTHER);
  const [customTopic, setCustomTopic] = useState(typeof params.topicName === "string" ? params.topicName : "");
  const [grade, setGrade] = useState(
    typeof params.grade === "string" && appVariant.allowedGrades.includes(params.grade)
      ? params.grade
      : appVariant.allowedGrades[0]
  );
  const [lesson, setLesson] = useState<LearningLesson | null>(null);
  const [loading, setLoading] = useState(false);
  const [autoGenerated, setAutoGenerated] = useState(false);

  useEffect(() => {
    readAppState().then((state) => {
      const active = state.profiles.find((entry) => entry.id === state.currentProfileId) ?? null;
      setProfile(active);
      setLanguage(active?.language ?? "en");
    });
  }, []);

  useEffect(() => {
    const requestedTopic = typeof params.topicName === "string" ? params.topicName.trim() : "";
    if (!requestedTopic || !selectedSubject) {
      setTopicId(OTHER);
      return;
    }
    const preset = selectedSubject.topics.find(
      (entry) => entry.label.toLowerCase() === requestedTopic.toLowerCase()
    );
    if (preset) {
      setTopicId(preset.id);
      setCustomTopic("");
    } else {
      setTopicId(OTHER);
      setCustomTopic(requestedTopic);
    }
  }, [params.topicName, selectedSubject?.id]);

  const generateLesson = async () => {
    const subjectName = subjectId === OTHER ? customSubject.trim() : selectedSubject?.name ?? "";
    const selectedTopic = selectedSubject?.topics.find((entry) => entry.id === topicId);
    const topicName = topicId === OTHER ? customTopic.trim() : selectedTopic?.label ?? "";
    if (!subjectName || !topicName || !grade) {
      Alert.alert(t(language, "learningHub"), "Please select or enter a subject, topic, and grade.");
      return;
    }

    setLoading(true);
    try {
      const result = await generateLearningLesson({
        subjectName,
        topicName,
        grade,
        context: typeof params.context === "string" ? params.context : undefined,
        profile,
      });
      setLesson(result);
    } catch {
      Alert.alert(t(language, "learningHub"), t(language, "unableGenerateLesson"));
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (autoGenerated || !profile || typeof params.context !== "string" || !params.context.trim()) {
      return;
    }
    setAutoGenerated(true);
    void generateLesson();
  }, [autoGenerated, profile, params.context]);

  return (
    <AppBackground webContentWidth="standard">
      <BackIconButton fallbackHref="/" />
      <View style={styles.hero}>
        <Text style={styles.title}>{t(language, "learningHub")}</Text>
        <Text style={styles.subtitle}>{t(language, "learningHubHint")}</Text>
      </View>

      <View style={styles.card}>
        <Text style={styles.label}>Subject</Text>
        <View style={styles.chips}>
          {subjects.map((entry) => (
            <Pressable key={entry.id} onPress={() => { setSubjectId(entry.id); setTopicId(OTHER); setLesson(null); }} style={[styles.chip, subjectId === entry.id && styles.chipActive]}>
              <Text style={[styles.chipText, subjectId === entry.id && styles.chipTextActive]}>{entry.name}</Text>
            </Pressable>
          ))}
          <Pressable onPress={() => { setSubjectId(OTHER); setTopicId(OTHER); setLesson(null); }} style={[styles.chip, subjectId === OTHER && styles.chipActive]}>
            <Text style={[styles.chipText, subjectId === OTHER && styles.chipTextActive]}>{t(language, "others")}</Text>
          </Pressable>
        </View>
        {subjectId === OTHER ? <TextInput value={customSubject} onChangeText={setCustomSubject} style={styles.input} placeholder={t(language, "enterCustomSubject")} placeholderTextColor="#7C8EA3" /> : null}

        <Text style={styles.label}>Topic</Text>
        <View style={styles.chips}>
          {(selectedSubject?.topics ?? []).map((entry) => (
            <Pressable key={entry.id} onPress={() => { setTopicId(entry.id); setLesson(null); }} style={[styles.chip, topicId === entry.id && styles.chipActive]}>
              <Text style={[styles.chipText, topicId === entry.id && styles.chipTextActive]}>{entry.label}</Text>
            </Pressable>
          ))}
          <Pressable onPress={() => { setTopicId(OTHER); setLesson(null); }} style={[styles.chip, topicId === OTHER && styles.chipActive]}>
            <Text style={[styles.chipText, topicId === OTHER && styles.chipTextActive]}>{t(language, "others")}</Text>
          </Pressable>
        </View>
        {topicId === OTHER ? <TextInput value={customTopic} onChangeText={setCustomTopic} style={styles.input} placeholder={t(language, "enterCustomTopic")} placeholderTextColor="#7C8EA3" /> : null}

        <Text style={styles.label}>Grade</Text>
        <View style={styles.chips}>
          {appVariant.allowedGrades.map((entry) => (
            <Pressable key={entry} onPress={() => { setGrade(entry); setLesson(null); }} style={[styles.chip, grade === entry && styles.chipActive]}>
              <Text style={[styles.chipText, grade === entry && styles.chipTextActive]}>{entry}</Text>
            </Pressable>
          ))}
        </View>
        <PrimaryButton label={t(language, "generateLesson")} onPress={generateLesson} loading={loading} style={styles.generateButton} />
      </View>

      {lesson ? (
        <View style={styles.lessonCard}>
          <Text style={styles.lessonTitle}>{lesson.title}</Text>
          <Text style={styles.sectionTitle}>{t(language, "lessonOverview")}</Text>
          <Text style={styles.body}>{lesson.overview}</Text>
          {lesson.sections.map((section, index) => <View key={`${section.heading}-${index}`}><Text style={styles.sectionTitle}>{section.heading}</Text><Text style={styles.body}>{section.content}</Text></View>)}
          <Text style={styles.sectionTitle}>{t(language, "lessonExamples")}</Text>
          {lesson.examples.map((entry, index) => <Text key={`example-${index}`} style={styles.listItem}>• {entry}</Text>)}
          <Text style={styles.sectionTitle}>{t(language, "lessonKeyPoints")}</Text>
          {lesson.keyPoints.map((entry, index) => <Text key={`point-${index}`} style={styles.listItem}>• {entry}</Text>)}
          <Text style={styles.sectionTitle}>{t(language, "lessonPracticeTip")}</Text>
          <Text style={styles.body}>{lesson.practiceTip}</Text>
          <PrimaryButton label={t(language, "backHome")} variant="ghost" onPress={() => router.replace("/")} style={styles.generateButton} />
        </View>
      ) : null}
    </AppBackground>
  );
}

const styles = StyleSheet.create({
  hero: { marginTop: 12, borderRadius: 26, padding: 20, backgroundColor: "rgba(255,255,255,0.12)" },
  title: { color: palette.white, fontSize: 30, fontWeight: "900" },
  subtitle: { color: "#E8F4FB", marginTop: 8, lineHeight: 22 },
  card: { marginTop: 18, borderRadius: 24, padding: 18, backgroundColor: palette.white, ...shadows.card },
  label: { color: palette.slate, fontWeight: "800", marginTop: 16, marginBottom: 8 },
  chips: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  chip: { borderRadius: 16, paddingHorizontal: 12, paddingVertical: 10, backgroundColor: "#F2F5F8" },
  chipActive: { backgroundColor: palette.navy },
  chipText: { color: palette.navy, fontWeight: "700" },
  chipTextActive: { color: palette.white },
  input: { minHeight: 50, marginTop: 10, borderRadius: 16, borderWidth: 1, borderColor: "#D6E0EA", backgroundColor: "#F9FBFD", paddingHorizontal: 14, color: palette.ink },
  generateButton: { marginTop: 20 },
  lessonCard: { marginTop: 18, borderRadius: 24, padding: 20, backgroundColor: palette.white, ...shadows.card },
  lessonTitle: { color: palette.ink, fontSize: 28, fontWeight: "900", lineHeight: 35 },
  sectionTitle: { color: palette.navy, fontSize: 18, fontWeight: "800", marginTop: 20, marginBottom: 6 },
  body: { color: palette.slate, lineHeight: 24 },
  listItem: { color: palette.slate, lineHeight: 24, marginTop: 4 },
});
