import { router, useLocalSearchParams } from "expo-router";
import * as Clipboard from "expo-clipboard";
import { useEffect, useMemo, useState } from "react";
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { AppBackground } from "../components/AppBackground";
import { BackIconButton } from "../components/BackIconButton";
import { PremiumFeatureDialog } from "../components/PremiumFeatureDialog";
import { PrimaryButton } from "../components/PrimaryButton";
import { appVariant } from "../lib/app-variant";
import { t } from "../lib/i18n";
import { canGenerateLearningHubToday } from "../lib/subscription";
import { readAppState, recordLearningHubGeneration } from "../lib/storage";
import { getLocalizedSubjects } from "../lib/subjects";
import { palette, shadows } from "../lib/theme";
import { askLearningHubQuestion, generateLearningLesson } from "../services/ai";
import type { AppLanguage, LearningLesson, SubscriptionTier, UserProfile } from "../types/app";

const OTHER = "other";

export default function LearningHubScreen() {
  const params = useLocalSearchParams<{
    subjectId?: string;
    subjectName?: string;
    topicName?: string;
    grade?: string;
    context?: string;
  }>();
  const [profile, setProfile] = useState<UserProfile | null>(null);
  const [language, setLanguage] = useState<AppLanguage>("en");
  const subjects = useMemo(() => getLocalizedSubjects(language), [language]);
  const initialSubjectId =
    typeof params.subjectId === "string" && subjects.some((entry) => entry.id === params.subjectId)
      ? params.subjectId
      : typeof params.subjectName === "string"
        ? OTHER
        : subjects[0]?.id ?? OTHER;
  const [subjectId, setSubjectId] = useState(initialSubjectId);
  const [customSubject, setCustomSubject] = useState(typeof params.subjectName === "string" ? params.subjectName : "");
  const selectedSubject = subjects.find((entry) => entry.id === subjectId) ?? null;
  const [topicId, setTopicId] = useState(OTHER);
  const [customTopic, setCustomTopic] = useState(typeof params.topicName === "string" ? params.topicName : "");
  const [grade, setGrade] = useState(
    typeof params.grade === "string" && appVariant.allowedGrades.includes(params.grade)
      ? params.grade
      : appVariant.allowedGrades[0]
  );
  const [lesson, setLesson] = useState<LearningLesson | null>(null);
  const [loading, setLoading] = useState(false);
  const [autoGenerated, setAutoGenerated] = useState(false);
  const [subjectDropdownOpen, setSubjectDropdownOpen] = useState(false);
  const [topicDropdownOpen, setTopicDropdownOpen] = useState(false);
  const [subscriptionTier, setSubscriptionTier] = useState<SubscriptionTier>("free");
  const [generationDates, setGenerationDates] = useState<string[]>([]);
  const [showUpgrade, setShowUpgrade] = useState(false);
  const [question, setQuestion] = useState("");
  const [answer, setAnswer] = useState("");
  const [answerLoading, setAnswerLoading] = useState(false);

  useEffect(() => {
    readAppState().then((state) => {
      const active = state.profiles.find((entry) => entry.id === state.currentProfileId) ?? null;
      setProfile(active);
      setLanguage(active?.language ?? "en");
      setSubscriptionTier(state.subscriptionTier);
      setGenerationDates(state.learningHubGenerationDates);
    });
  }, []);

  useEffect(() => {
    const requestedTopic = typeof params.topicName === "string" ? params.topicName.trim() : "";
    if (!requestedTopic || !selectedSubject) {
      setTopicId(OTHER);
      return;
    }
    const preset = selectedSubject.topics.find(
      (entry) => entry.label.toLowerCase() === requestedTopic.toLowerCase()
    );
    if (preset) {
      setTopicId(preset.id);
      setCustomTopic("");
    } else {
      setTopicId(OTHER);
      setCustomTopic(requestedTopic);
    }
  }, [params.topicName, selectedSubject?.id]);

  const generateLesson = async () => {
    const subjectName = subjectId === OTHER ? customSubject.trim() : selectedSubject?.name ?? "";
    const selectedTopic = selectedSubject?.topics.find((entry) => entry.id === topicId);
    const topicName = topicId === OTHER ? customTopic.trim() : selectedTopic?.label ?? "";
    if (!subjectName || !topicName || !grade) {
      Alert.alert(t(language, "learningHub"), "Please select or enter a subject, topic, and grade.");
      return;
    }

    if (!canGenerateLearningHubToday(subscriptionTier, generationDates)) {
      setShowUpgrade(true);
      return;
    }

    setLoading(true);
    try {
      const result = await generateLearningLesson({
        subjectName,
        topicName,
        grade,
        context: typeof params.context === "string" ? params.context : undefined,
        profile,
      });
      setLesson(result);
      if (subscriptionTier === "free") {
        const generatedAt = new Date().toISOString();
        const state = await recordLearningHubGeneration(generatedAt);
        setGenerationDates(state.learningHubGenerationDates);
      }
    } catch {
      Alert.alert(t(language, "learningHub"), t(language, "unableGenerateLesson"));
    } finally {
      setLoading(false);
    }
  };

  const askQuestion = async () => {
    const trimmedQuestion = question.trim();
    if (!trimmedQuestion) {
      Alert.alert(t(language, "askAQuestion"), t(language, "enterQuestion"));
      return;
    }
    if (!canGenerateLearningHubToday(subscriptionTier, generationDates)) {
      setShowUpgrade(true);
      return;
    }

    setAnswerLoading(true);
    try {
      const result = await askLearningHubQuestion({
        question: trimmedQuestion,
      });
      setAnswer(result);
      if (subscriptionTier === "free") {
        const state = await recordLearningHubGeneration(new Date().toISOString());
        setGenerationDates(state.learningHubGenerationDates);
      }
    } catch {
      Alert.alert(t(language, "askAQuestion"), t(language, "unableAnswerQuestion"));
    } finally {
      setAnswerLoading(false);
    }
  };

  const copyLesson = async () => {
    if (!lesson) {
      return;
    }
    const text = [
      lesson.title,
      lesson.overview,
      ...lesson.sections.flatMap((section) => [section.heading, section.content]),
      t(language, "lessonExamples"),
      ...lesson.examples.map((entry) => `- ${entry}`),
      t(language, "lessonKeyPoints"),
      ...lesson.keyPoints.map((entry) => `- ${entry}`),
      t(language, "lessonPracticeTip"),
      lesson.practiceTip,
    ].join("\n\n");
    await Clipboard.setStringAsync(text);
    Alert.alert(t(language, "lessonCopied"));
  };

  const copyAnswer = async () => {
    if (!answer) {
      return;
    }
    await Clipboard.setStringAsync(answer);
    Alert.alert(t(language, "answerCopied"));
  };

  useEffect(() => {
    if (autoGenerated || !profile || typeof params.context !== "string" || !params.context.trim()) {
      return;
    }
    setAutoGenerated(true);
    void generateLesson();
  }, [autoGenerated, profile, params.context]);

  return (
    <AppBackground webContentWidth="standard">
      <BackIconButton fallbackHref="/" />
      <View style={styles.hero}>
        <Text style={styles.title}>{t(language, "learningHub")}</Text>
        <Text style={styles.subtitle}>{t(language, "learningHubHint")}</Text>
      </View>

      <View style={styles.card}>
        <Text style={styles.label}>Subject</Text>
        <Pressable onPress={() => { setSubjectDropdownOpen((value) => !value); setTopicDropdownOpen(false); }} style={styles.dropdownTrigger}>
          <Text style={styles.dropdownValue}>{subjectId === OTHER ? customSubject || t(language, "others") : selectedSubject?.name}</Text>
          <Text style={styles.dropdownChevron}>{subjectDropdownOpen ? "▲" : "▼"}</Text>
        </Pressable>
        {subjectDropdownOpen ? (
          <View style={styles.dropdownMenu}>
            <ScrollView nestedScrollEnabled style={styles.dropdownScroll}>
              {[...subjects.map((entry) => ({ id: entry.id, label: entry.name })), { id: OTHER, label: t(language, "others") }].map((entry) => (
                <Pressable key={entry.id} onPress={() => { setSubjectId(entry.id); setTopicId(OTHER); setLesson(null); setSubjectDropdownOpen(false); }} style={[styles.dropdownItem, subjectId === entry.id && styles.dropdownItemActive]}>
                  <Text style={[styles.dropdownItemText, subjectId === entry.id && styles.dropdownItemTextActive]}>{entry.label}</Text>
                </Pressable>
              ))}
            </ScrollView>
          </View>
        ) : null}
        {subjectId === OTHER ? <TextInput value={customSubject} onChangeText={setCustomSubject} style={styles.input} placeholder={t(language, "enterCustomSubject")} placeholderTextColor="#7C8EA3" /> : null}

        <Text style={styles.label}>Topic</Text>
        <Pressable onPress={() => { setTopicDropdownOpen((value) => !value); setSubjectDropdownOpen(false); }} style={styles.dropdownTrigger}>
          <Text style={styles.dropdownValue}>{topicId === OTHER ? customTopic || t(language, "others") : selectedSubject?.topics.find((entry) => entry.id === topicId)?.label}</Text>
          <Text style={styles.dropdownChevron}>{topicDropdownOpen ? "▲" : "▼"}</Text>
        </Pressable>
        {topicDropdownOpen ? (
          <View style={styles.dropdownMenu}>
            <ScrollView nestedScrollEnabled style={styles.dropdownScroll}>
              {[...(selectedSubject?.topics ?? []).map((entry) => ({ id: entry.id, label: entry.label })), { id: OTHER, label: t(language, "others") }].map((entry) => (
                <Pressable key={entry.id} onPress={() => { setTopicId(entry.id); setLesson(null); setTopicDropdownOpen(false); }} style={[styles.dropdownItem, topicId === entry.id && styles.dropdownItemActive]}>
                  <Text style={[styles.dropdownItemText, topicId === entry.id && styles.dropdownItemTextActive]}>{entry.label}</Text>
                </Pressable>
              ))}
            </ScrollView>
          </View>
        ) : null}
        {topicId === OTHER ? <TextInput value={customTopic} onChangeText={setCustomTopic} style={styles.input} placeholder={t(language, "enterCustomTopic")} placeholderTextColor="#7C8EA3" /> : null}

        <Text style={styles.label}>Grade</Text>
        <View style={styles.chips}>
          {appVariant.allowedGrades.map((entry) => (
            <Pressable key={entry} onPress={() => { setGrade(entry); setLesson(null); }} style={[styles.chip, grade === entry && styles.chipActive]}>
              <Text style={[styles.chipText, grade === entry && styles.chipTextActive]}>{entry}</Text>
            </Pressable>
          ))}
        </View>
        <PrimaryButton label={t(language, "generateLesson")} onPress={generateLesson} loading={loading} style={styles.generateButton} />
      </View>

      <View style={styles.card}>
        <Text style={styles.askTitle}>{t(language, "askAQuestion")}</Text>
        <Text style={styles.askHint}>{t(language, "askQuestionHint")}</Text>
        <TextInput
          value={question}
          onChangeText={(value) => { setQuestion(value); setAnswer(""); }}
          style={[styles.input, styles.questionInput]}
          placeholder={t(language, "enterQuestion")}
          placeholderTextColor="#7C8EA3"
          multiline
          textAlignVertical="top"
        />
        <PrimaryButton label={t(language, "submitQuestion")} onPress={askQuestion} loading={answerLoading} style={styles.generateButton} />
        {answer ? (
          <View style={styles.answerCard}>
            <View style={styles.answerHeader}>
              <Text style={[styles.sectionTitle, styles.answerTitle]}>{t(language, "questionAnswer")}</Text>
              <PrimaryButton label={t(language, "copyLesson")} variant="secondary" compact onPress={copyAnswer} style={styles.copyButton} />
            </View>
            <Text style={styles.body}>{answer}</Text>
          </View>
        ) : null}
      </View>

      {lesson ? (
        <View style={styles.lessonCard}>
          <View style={styles.lessonHeader}>
            <Text style={styles.lessonTitle}>{lesson.title}</Text>
            <PrimaryButton label={t(language, "copyLesson")} variant="secondary" compact onPress={copyLesson} style={styles.copyButton} />
          </View>
          <Text style={styles.sectionTitle}>{t(language, "lessonOverview")}</Text>
          <Text style={styles.body}>{lesson.overview}</Text>
          {lesson.sections.map((section, index) => <View key={`${section.heading}-${index}`}><Text style={styles.sectionTitle}>{section.heading}</Text><Text style={styles.body}>{section.content}</Text></View>)}
          <Text style={styles.sectionTitle}>{t(language, "lessonExamples")}</Text>
          {lesson.examples.map((entry, index) => <Text key={`example-${index}`} style={styles.listItem}>• {entry}</Text>)}
          <Text style={styles.sectionTitle}>{t(language, "lessonKeyPoints")}</Text>
          {lesson.keyPoints.map((entry, index) => <Text key={`point-${index}`} style={styles.listItem}>• {entry}</Text>)}
          <Text style={styles.sectionTitle}>{t(language, "lessonPracticeTip")}</Text>
          <Text style={styles.body}>{lesson.practiceTip}</Text>
          <PrimaryButton label={t(language, "backHome")} variant="ghost" onPress={() => router.replace("/")} style={styles.generateButton} />
        </View>
      ) : null}
      <PremiumFeatureDialog
        visible={showUpgrade}
        title={t(language, "upgradeToPro")}
        message={t(language, "learningHubDailyLimit")}
        upgradeLabel={t(language, "upgradeToPro")}
        cancelLabel={t(language, "cancel")}
        onClose={() => setShowUpgrade(false)}
        onUpgrade={() => {
          setShowUpgrade(false);
          router.push({ pathname: "/subscription", params: { source: "learning-hub" } } as never);
        }}
      />
    </AppBackground>
  );
}

const styles = StyleSheet.create({
  hero: { marginTop: 12, borderRadius: 26, padding: 20, backgroundColor: "rgba(255,255,255,0.12)" },
  title: { color: palette.white, fontSize: 30, fontWeight: "900" },
  subtitle: { color: "#E8F4FB", marginTop: 8, lineHeight: 22 },
  card: { marginTop: 18, borderRadius: 24, padding: 18, backgroundColor: palette.white, ...shadows.card },
  label: { color: palette.slate, fontWeight: "800", marginTop: 16, marginBottom: 8 },
  chips: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  chip: { borderRadius: 16, paddingHorizontal: 12, paddingVertical: 10, backgroundColor: "#F2F5F8" },
  chipActive: { backgroundColor: palette.navy },
  chipText: { color: palette.navy, fontWeight: "700" },
  chipTextActive: { color: palette.white },
  dropdownTrigger: { minHeight: 52, borderRadius: 16, borderWidth: 1, borderColor: "#D6E0EA", backgroundColor: "#F9FBFD", paddingHorizontal: 14, flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 12 },
  dropdownValue: { flex: 1, color: palette.ink, fontWeight: "700" },
  dropdownChevron: { color: palette.navy, fontSize: 12, fontWeight: "900" },
  dropdownMenu: { marginTop: 8, borderRadius: 16, borderWidth: 1, borderColor: "#D6E0EA", backgroundColor: palette.white, overflow: "hidden" },
  dropdownScroll: { maxHeight: 260 },
  dropdownItem: { paddingHorizontal: 14, paddingVertical: 13, borderBottomWidth: 1, borderBottomColor: "#EEF3F7" },
  dropdownItemActive: { backgroundColor: "#EAF7FD" },
  dropdownItemText: { color: palette.ink, fontWeight: "700" },
  dropdownItemTextActive: { color: palette.navy },
  input: { minHeight: 50, marginTop: 10, borderRadius: 16, borderWidth: 1, borderColor: "#D6E0EA", backgroundColor: "#F9FBFD", paddingHorizontal: 14, color: palette.ink },
  generateButton: { marginTop: 20 },
  askTitle: { color: palette.ink, fontSize: 22, fontWeight: "900" },
  askHint: { color: palette.slate, lineHeight: 22, marginTop: 6 },
  questionInput: { minHeight: 110, paddingTop: 14 },
  answerCard: { marginTop: 18, borderRadius: 18, padding: 16, backgroundColor: "#F3F9FC" },
  answerHeader: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: 12, marginBottom: 8 },
  answerTitle: { flex: 1, marginTop: 0, marginBottom: 0 },
  lessonCard: { marginTop: 18, borderRadius: 24, padding: 20, backgroundColor: palette.white, ...shadows.card },
  lessonHeader: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: 12 },
  lessonTitle: { flex: 1, color: palette.ink, fontSize: 28, fontWeight: "900", lineHeight: 35 },
  copyButton: { width: 96, maxWidth: 96 },
  sectionTitle: { color: palette.navy, fontSize: 18, fontWeight: "800", marginTop: 20, marginBottom: 6 },
  body: { color: palette.slate, lineHeight: 24 },
  listItem: { color: palette.slate, lineHeight: 24, marginTop: 4 },
});
