import { useEffect, useState } from "react";
import { Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { AppBackground } from "../components/AppBackground";
import { palette, shadows } from "../lib/theme";
import { createSchool, getSchoolOwnerDashboard } from "../services/ai";
import type { SchoolOwnerDashboardResponse } from "../types/app";

export default function SchoolOwnerScreen() {
  const [data, setData] = useState<SchoolOwnerDashboardResponse | null>(null);
  const [name, setName] = useState(""); const [students, setStudents] = useState("500"); const [teachers, setTeachers] = useState("50");
  const [startDate, setStartDate] = useState(new Date().toISOString().slice(0, 10)); const [endDate, setEndDate] = useState(""); const [error, setError] = useState("");
  async function load() { try { setData(await getSchoolOwnerDashboard()); setError(""); } catch (caught) { setError(caught instanceof Error ? caught.message : "Owner access is not configured for this account."); } }
  useEffect(() => { void load(); }, []);
  async function addSchool() { try { await createSchool({ name, plan: "term", startAt: new Date(`${startDate}T00:00:00`).getTime(), endAt: new Date(`${endDate}T23:59:59`).getTime(), studentSeatLimit: Number(students), teacherSeatLimit: Number(teachers), allowedVariants: ["children", "teens", "uni"], gracePeriodDays: 0 }); setName(""); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to create school."); } }
  return <AppBackground webContentWidth="wide"><View style={styles.hero}><Text style={styles.eyebrow}>QUIKS OWNER CONTROL</Text><Text style={styles.title}>Quiks School portfolio</Text><Text style={styles.light}>Institutional enrolment, seats, licence expiry and operational visibility.</Text></View>{error ? <Text style={styles.error}>{error}</Text> : null}
    {data ? <View style={styles.metrics}>{Object.entries(data.totals).map(([key, value]) => <View key={key} style={styles.metric}><Text style={styles.number}>{value}</Text><Text style={styles.metricLabel}>{key.replace(/([A-Z])/g, " $1")}</Text></View>)}</View> : null}
    <View style={styles.grid}><View style={styles.card}><Text style={styles.heading}>Create school licence</Text><TextInput value={name} onChangeText={setName} placeholder="School name" style={styles.input}/><View style={styles.row}><TextInput value={students} onChangeText={setStudents} keyboardType="number-pad" placeholder="Student seats" style={[styles.input, styles.flex]}/><TextInput value={teachers} onChangeText={setTeachers} keyboardType="number-pad" placeholder="Teacher seats" style={[styles.input, styles.flex]}/></View><Text style={styles.label}>Starts</Text><TextInput value={startDate} onChangeText={setStartDate} placeholder="YYYY-MM-DD" style={styles.input}/><Text style={styles.label}>Expires</Text><TextInput value={endDate} onChangeText={setEndDate} placeholder="YYYY-MM-DD" style={styles.input}/><Pressable style={styles.button} onPress={addSchool}><Text style={styles.buttonText}>Create Quiks School account</Text></Pressable></View>
      <View style={styles.card}><Text style={styles.heading}>Schools</Text>{data?.schools.map((school) => <View key={school.schoolId} style={styles.school}><Text style={styles.schoolName}>{school.name}</Text><Text style={styles.meta}>Code {school.schoolCode} · {school.status}</Text><Text style={styles.meta}>{school.studentCount}/{school.licence.studentSeatLimit} students · {school.teacherCount}/{school.licence.teacherSeatLimit} teachers</Text><Text style={styles.meta}>Expires {new Date(school.licence.endAt).toLocaleDateString()} · {school.seatUsagePercent}% seats used</Text></View>)}</View></View>
  </AppBackground>;
}
const styles = StyleSheet.create({ hero: { backgroundColor: palette.navy, borderRadius: 26, padding: 24, marginBottom: 16 }, eyebrow: { color: "#70E2D8", fontWeight: "900", letterSpacing: 1.5 }, title: { color: "white", fontSize: 31, fontWeight: "900", marginTop: 7 }, light: { color: "#D8E8EE", marginTop: 7 }, metrics: { flexDirection: "row", flexWrap: "wrap", gap: 10, marginBottom: 16 }, metric: { backgroundColor: "white", borderRadius: 18, padding: 16, minWidth: 145, flexGrow: 1, ...shadows.card }, number: { color: palette.navy, fontSize: 26, fontWeight: "900" }, metricLabel: { color: "#587180", textTransform: "capitalize" }, grid: { flexDirection: "row", flexWrap: "wrap", gap: 16 }, card: { backgroundColor: "white", borderRadius: 24, padding: 20, flexGrow: 1, flexBasis: 440, ...shadows.card }, heading: { color: palette.navy, fontSize: 22, fontWeight: "900", marginBottom: 10 }, input: { backgroundColor: "#F6F9FB", borderWidth: 1, borderColor: "#D4E0E7", borderRadius: 13, padding: 13, marginVertical: 6 }, row: { flexDirection: "row", gap: 8 }, flex: { flex: 1 }, label: { color: palette.navy, fontWeight: "800", marginTop: 5 }, button: { backgroundColor: palette.navy, borderRadius: 14, padding: 15, alignItems: "center", marginTop: 10 }, buttonText: { color: "white", fontWeight: "900" }, school: { paddingVertical: 13, borderTopColor: "#E4ECF1", borderTopWidth: 1 }, schoolName: { color: palette.navy, fontSize: 17, fontWeight: "900" }, meta: { color: "#587180", marginTop: 4 }, error: { color: "#B42318", backgroundColor: "#FFF0EE", padding: 12, borderRadius: 12, marginBottom: 12 } });
