import type { Difficulty, Question, QuestionRequest } from "../types/app";

type GradeBucket = "lower-primary" | "upper-primary";

interface BankQuestion extends Question {
  subjectId: string;
  difficulty: Difficulty;
  gradeBucket: GradeBucket;
}

const bank: BankQuestion[] = [
  {
    id: "arith-lp-beg-1",
    subjectId: "arithmetic",
    difficulty: "Beginner",
    gradeBucket: "lower-primary",
    prompt: "What is 7 + 5?",
    options: ["10", "11", "12", "13"],
    answer: "12",
    explanation: "Add 7 and 5 together to get 12.",
  },
  {
    id: "arith-lp-beg-2",
    subjectId: "arithmetic",
    difficulty: "Beginner",
    gradeBucket: "lower-primary",
    prompt: "What is 15 - 6?",
    options: ["7", "8", "9", "10"],
    answer: "9",
    explanation: "Starting from 15 and taking away 6 leaves 9.",
  },
  {
    id: "arith-lp-beg-3",
    subjectId: "arithmetic",
    difficulty: "Beginner",
    gradeBucket: "lower-primary",
    prompt: "Which number is greater than 18?",
    options: ["16", "17", "19", "15"],
    answer: "19",
    explanation: "19 comes after 18, so it is greater.",
  },
  {
    id: "arith-lp-beg-4",
    subjectId: "arithmetic",
    difficulty: "Beginner",
    gradeBucket: "lower-primary",
    prompt: "What is 4 + 4 + 4?",
    options: ["10", "11", "12", "13"],
    answer: "12",
    explanation: "4 added three times equals 12.",
  },
  {
    id: "arith-lp-beg-5",
    subjectId: "arithmetic",
    difficulty: "Beginner",
    gradeBucket: "lower-primary",
    prompt: "How many tens are in the number 30?",
    options: ["1", "2", "3", "4"],
    answer: "3",
    explanation: "30 is made of three groups of ten.",
  },
  {
    id: "arith-lp-beg-6",
    subjectId: "arithmetic",
    difficulty: "Beginner",
    gradeBucket: "lower-primary",
    prompt: "What is 3 × 2?",
    options: ["5", "6", "7", "8"],
    answer: "6",
    explanation: "3 groups of 2 make 6.",
  },
  {
    id: "arith-lp-beg-7",
    subjectId: "arithmetic",
    difficulty: "Beginner",
    gradeBucket: "lower-primary",
    prompt: "What number comes before 40?",
    options: ["38", "39", "41", "42"],
    answer: "39",
    explanation: "39 is one less than 40.",
  },
  {
    id: "arith-lp-beg-8",
    subjectId: "arithmetic",
    difficulty: "Beginner",
    gradeBucket: "lower-primary",
    prompt: "If you have 10 oranges and give away 3, how many are left?",
    options: ["6", "7", "8", "9"],
    answer: "7",
    explanation: "10 minus 3 equals 7.",
  },
  {
    id: "arith-lp-beg-9",
    subjectId: "arithmetic",
    difficulty: "Beginner",
    gradeBucket: "lower-primary",
    prompt: "Which of these is an even number?",
    options: ["7", "9", "11", "12"],
    answer: "12",
    explanation: "Even numbers can be divided into two equal groups. 12 is even.",
  },
  {
    id: "arith-lp-beg-10",
    subjectId: "arithmetic",
    difficulty: "Beginner",
    gradeBucket: "lower-primary",
    prompt: "What is half of 8?",
    options: ["2", "3", "4", "5"],
    answer: "4",
    explanation: "Half means two equal parts. Half of 8 is 4.",
  },
  {
    id: "arith-lp-beg-11",
    subjectId: "arithmetic",
    difficulty: "Beginner",
    gradeBucket: "lower-primary",
    prompt: "Which sign makes this true: 9 __ 6?",
    options: ["+", "-", ">", "<"],
    answer: ">",
    explanation: "9 is greater than 6, so the correct sign is greater than.",
  },
  {
    id: "arith-lp-beg-12",
    subjectId: "arithmetic",
    difficulty: "Beginner",
    gradeBucket: "lower-primary",
    prompt: "What is 20 + 10?",
    options: ["20", "25", "30", "40"],
    answer: "30",
    explanation: "Adding one ten to 20 gives 30.",
  },
  {
    id: "arith-up-beg-1",
    subjectId: "arithmetic",
    difficulty: "Beginner",
    gradeBucket: "upper-primary",
    prompt: "What is 48 + 27?",
    options: ["65", "75", "76", "85"],
    answer: "75",
    explanation: "48 plus 27 equals 75.",
  },
  {
    id: "arith-up-beg-2",
    subjectId: "arithmetic",
    difficulty: "Beginner",
    gradeBucket: "upper-primary",
    prompt: "What is 96 - 34?",
    options: ["52", "62", "72", "82"],
    answer: "62",
    explanation: "Subtract 34 from 96 to get 62.",
  },
  {
    id: "arith-up-beg-3",
    subjectId: "arithmetic",
    difficulty: "Beginner",
    gradeBucket: "upper-primary",
    prompt: "What is 6 × 7?",
    options: ["36", "40", "42", "48"],
    answer: "42",
    explanation: "6 multiplied by 7 equals 42.",
  },
  {
    id: "arith-up-beg-4",
    subjectId: "arithmetic",
    difficulty: "Beginner",
    gradeBucket: "upper-primary",
    prompt: "What is 24 ÷ 6?",
    options: ["3", "4", "5", "6"],
    answer: "4",
    explanation: "24 shared equally into 6 groups gives 4 in each group.",
  },
  {
    id: "arith-up-beg-5",
    subjectId: "arithmetic",
    difficulty: "Beginner",
    gradeBucket: "upper-primary",
    prompt: "Which fraction is equal to one half?",
    options: ["1/3", "2/4", "3/4", "2/3"],
    answer: "2/4",
    explanation: "2/4 simplifies to 1/2.",
  },
  {
    id: "arith-up-beg-6",
    subjectId: "arithmetic",
    difficulty: "Beginner",
    gradeBucket: "upper-primary",
    prompt: "What is the place value of 5 in 352?",
    options: ["Ones", "Tens", "Hundreds", "Thousands"],
    answer: "Tens",
    explanation: "In 352, the digit 5 is in the tens place.",
  },
  {
    id: "arith-up-beg-7",
    subjectId: "arithmetic",
    difficulty: "Beginner",
    gradeBucket: "upper-primary",
    prompt: "Round 67 to the nearest ten.",
    options: ["60", "65", "70", "80"],
    answer: "70",
    explanation: "67 is closer to 70 than to 60.",
  },
  {
    id: "arith-up-beg-8",
    subjectId: "arithmetic",
    difficulty: "Beginner",
    gradeBucket: "upper-primary",
    prompt: "What is 25% of 20?",
    options: ["4", "5", "10", "15"],
    answer: "5",
    explanation: "25% means one quarter. One quarter of 20 is 5.",
  },
  {
    id: "arith-up-beg-9",
    subjectId: "arithmetic",
    difficulty: "Beginner",
    gradeBucket: "upper-primary",
    prompt: "What is the perimeter of a square with side 4 cm?",
    options: ["8 cm", "12 cm", "16 cm", "20 cm"],
    answer: "16 cm",
    explanation: "A square has 4 equal sides, so 4 + 4 + 4 + 4 = 16 cm.",
  },
  {
    id: "arith-up-beg-10",
    subjectId: "arithmetic",
    difficulty: "Beginner",
    gradeBucket: "upper-primary",
    prompt: "What decimal is the same as 3/10?",
    options: ["0.03", "0.3", "3.0", "30.0"],
    answer: "0.3",
    explanation: "Three tenths is written as 0.3.",
  },
  {
    id: "eng-lp-beg-1",
    subjectId: "english",
    difficulty: "Beginner",
    gradeBucket: "lower-primary",
    prompt: "Which word names an animal?",
    options: ["table", "lion", "book", "chair"],
    answer: "lion",
    explanation: "A lion is an animal. The others are things.",
  },
  {
    id: "eng-lp-beg-2",
    subjectId: "english",
    difficulty: "Beginner",
    gradeBucket: "lower-primary",
    prompt: "Choose the word with the short 'a' sound.",
    options: ["cake", "cat", "kite", "cube"],
    answer: "cat",
    explanation: "Cat has the short 'a' sound.",
  },
  {
    id: "eng-lp-beg-3",
    subjectId: "english",
    difficulty: "Beginner",
    gradeBucket: "lower-primary",
    prompt: "Which word is the opposite of 'big'?",
    options: ["small", "tall", "wide", "long"],
    answer: "small",
    explanation: "Small is the opposite of big.",
  },
  {
    id: "eng-lp-beg-4",
    subjectId: "english",
    difficulty: "Beginner",
    gradeBucket: "lower-primary",
    prompt: "Which sentence begins with a capital letter?",
    options: ["my dog is brown.", "the sun is hot.", "We play outside.", "birds can fly."],
    answer: "We play outside.",
    explanation: "A sentence should begin with a capital letter. 'We play outside.' does that correctly.",
  },
  {
    id: "eng-lp-beg-5",
    subjectId: "english",
    difficulty: "Beginner",
    gradeBucket: "lower-primary",
    prompt: "Which word rhymes with 'ball'?",
    options: ["bell", "wall", "bird", "book"],
    answer: "wall",
    explanation: "Ball and wall have the same ending sound.",
  },
  {
    id: "eng-lp-beg-6",
    subjectId: "english",
    difficulty: "Beginner",
    gradeBucket: "lower-primary",
    prompt: "Which one is a correct plural form?",
    options: ["one cats", "two cat", "two cats", "cat two"],
    answer: "two cats",
    explanation: "We add 's' to cat when there is more than one.",
  },
  {
    id: "eng-lp-beg-7",
    subjectId: "english",
    difficulty: "Beginner",
    gradeBucket: "lower-primary",
    prompt: "Choose the correct missing word: 'I ___ happy.'",
    options: ["am", "is", "are", "be"],
    answer: "am",
    explanation: "With 'I', the correct verb is 'am'.",
  },
  {
    id: "eng-lp-beg-8",
    subjectId: "english",
    difficulty: "Beginner",
    gradeBucket: "lower-primary",
    prompt: "Which word is a naming word (noun)?",
    options: ["run", "blue", "teacher", "quickly"],
    answer: "teacher",
    explanation: "Teacher names a person, so it is a noun.",
  },
  {
    id: "eng-lp-beg-9",
    subjectId: "english",
    difficulty: "Beginner",
    gradeBucket: "lower-primary",
    prompt: "What punctuation mark ends this sentence? 'I like apples___'",
    options: ["?", ".", ",", "!"],
    answer: ".",
    explanation: "A statement usually ends with a full stop.",
  },
  {
    id: "eng-lp-beg-10",
    subjectId: "english",
    difficulty: "Beginner",
    gradeBucket: "lower-primary",
    prompt: "Which word means the same as 'glad'?",
    options: ["sad", "happy", "cold", "slow"],
    answer: "happy",
    explanation: "Glad and happy are similar in meaning.",
  },
  {
    id: "eng-lp-beg-11",
    subjectId: "english",
    difficulty: "Beginner",
    gradeBucket: "lower-primary",
    prompt: "Choose the word that completes the sentence: 'The boy can ___ fast.'",
    options: ["runs", "run", "running", "raned"],
    answer: "run",
    explanation: "After 'can', we use the base form of the verb: run.",
  },
  {
    id: "eng-lp-beg-12",
    subjectId: "english",
    difficulty: "Beginner",
    gradeBucket: "lower-primary",
    prompt: "Which word starts with the same sound as 'sun'?",
    options: ["sock", "moon", "hat", "pen"],
    answer: "sock",
    explanation: "Sun and sock both begin with the /s/ sound.",
  },
  {
    id: "eng-up-beg-1",
    subjectId: "english",
    difficulty: "Beginner",
    gradeBucket: "upper-primary",
    prompt: "Which sentence is written correctly?",
    options: ["she likes reading.", "She likes reading.", "she Likes reading.", "She likes Reading."],
    answer: "She likes reading.",
    explanation: "A sentence should begin with a capital letter and use lowercase appropriately.",
  },
  {
    id: "eng-up-beg-2",
    subjectId: "english",
    difficulty: "Beginner",
    gradeBucket: "upper-primary",
    prompt: "Choose the adjective in this sentence: 'The tall girl waved.'",
    options: ["The", "tall", "girl", "waved"],
    answer: "tall",
    explanation: "Tall describes the girl, so it is the adjective.",
  },
  {
    id: "eng-up-beg-3",
    subjectId: "english",
    difficulty: "Beginner",
    gradeBucket: "upper-primary",
    prompt: "What is the past tense of 'go'?",
    options: ["goed", "gone", "went", "going"],
    answer: "went",
    explanation: "The correct past tense of 'go' is 'went'.",
  },
  {
    id: "eng-up-beg-4",
    subjectId: "english",
    difficulty: "Beginner",
    gradeBucket: "upper-primary",
    prompt: "Which word is a synonym for 'quick'?",
    options: ["slow", "fast", "weak", "late"],
    answer: "fast",
    explanation: "Fast means nearly the same as quick.",
  },
  {
    id: "eng-up-beg-5",
    subjectId: "english",
    difficulty: "Beginner",
    gradeBucket: "upper-primary",
    prompt: "Choose the correct word: 'The pupils ___ in the hall.'",
    options: ["is", "are", "was", "am"],
    answer: "are",
    explanation: "Pupils is plural, so the correct verb is 'are'.",
  },
  {
    id: "eng-up-beg-6",
    subjectId: "english",
    difficulty: "Beginner",
    gradeBucket: "upper-primary",
    prompt: "Which punctuation mark is used at the end of a question?",
    options: [".", ",", "?", "!"],
    answer: "?",
    explanation: "Questions end with a question mark.",
  },
  {
    id: "eng-up-beg-7",
    subjectId: "english",
    difficulty: "Beginner",
    gradeBucket: "upper-primary",
    prompt: "Choose the pronoun that can replace 'Mary and I'.",
    options: ["He", "She", "We", "They"],
    answer: "We",
    explanation: "Mary and I refers to two people including the speaker, so 'we' is correct.",
  },
  {
    id: "eng-up-beg-8",
    subjectId: "english",
    difficulty: "Beginner",
    gradeBucket: "upper-primary",
    prompt: "Which word is an antonym of 'empty'?",
    options: ["full", "wide", "light", "open"],
    answer: "full",
    explanation: "Full is the opposite of empty.",
  },
  {
    id: "eng-up-beg-9",
    subjectId: "english",
    difficulty: "Beginner",
    gradeBucket: "upper-primary",
    prompt: "What is the main verb in this sentence: 'They played football yesterday.'",
    options: ["They", "played", "football", "yesterday"],
    answer: "played",
    explanation: "Played shows the action in the sentence.",
  },
  {
    id: "eng-up-beg-10",
    subjectId: "english",
    difficulty: "Beginner",
    gradeBucket: "upper-primary",
    prompt: "Choose the correct spelling.",
    options: ["becos", "because", "becouse", "because"],
    answer: "because",
    explanation: "Because is the correct spelling.",
  },
  {
    id: "phy-lp-beg-1",
    subjectId: "physics",
    difficulty: "Beginner",
    gradeBucket: "lower-primary",
    prompt: "Which of these can give us light?",
    options: ["Stone", "Sun", "Shoe", "Spoon"],
    answer: "Sun",
    explanation: "The sun is a natural source of light.",
  },
  {
    id: "phy-lp-beg-2",
    subjectId: "physics",
    difficulty: "Beginner",
    gradeBucket: "lower-primary",
    prompt: "Which object will move faster down a slide?",
    options: ["A parked bag", "A rolling ball", "A tree", "A wall"],
    answer: "A rolling ball",
    explanation: "A rolling ball is already in motion and can move down the slide.",
  },
  {
    id: "phy-lp-beg-3",
    subjectId: "physics",
    difficulty: "Beginner",
    gradeBucket: "lower-primary",
    prompt: "Which sense helps you hear sound?",
    options: ["Touch", "Taste", "Hearing", "Smell"],
    answer: "Hearing",
    explanation: "We hear sound with our ears.",
  },
  {
    id: "phy-lp-beg-4",
    subjectId: "physics",
    difficulty: "Beginner",
    gradeBucket: "lower-primary",
    prompt: "What happens when you push a toy car?",
    options: ["It sleeps", "It moves", "It melts", "It disappears"],
    answer: "It moves",
    explanation: "A push is a force that can make an object move.",
  },
  {
    id: "phy-lp-beg-5",
    subjectId: "physics",
    difficulty: "Beginner",
    gradeBucket: "lower-primary",
    prompt: "Which one is an example of a magnet attracting metal?",
    options: ["A cup floating", "A magnet pulling pins", "A book opening", "A leaf falling"],
    answer: "A magnet pulling pins",
    explanation: "Magnets attract some metals such as iron and steel.",
  },
  {
    id: "phy-lp-beg-6",
    subjectId: "physics",
    difficulty: "Beginner",
    gradeBucket: "lower-primary",
    prompt: "Which object is likely to sink in water?",
    options: ["Plastic bottle cap", "Leaf", "Small stone", "Empty paper cup"],
    answer: "Small stone",
    explanation: "A small stone is denser than water and will usually sink.",
  },
  {
    id: "phy-lp-beg-7",
    subjectId: "physics",
    difficulty: "Beginner",
    gradeBucket: "lower-primary",
    prompt: "Which of these gives off heat?",
    options: ["Ice cube", "Fire", "Pillow", "Bucket"],
    answer: "Fire",
    explanation: "Fire produces heat energy.",
  },
  {
    id: "phy-lp-beg-8",
    subjectId: "physics",
    difficulty: "Beginner",
    gradeBucket: "lower-primary",
    prompt: "What do we use to see objects clearly?",
    options: ["Darkness", "Light", "Silence", "Wind"],
    answer: "Light",
    explanation: "We need light to see objects.",
  },
  {
    id: "phy-lp-beg-9",
    subjectId: "physics",
    difficulty: "Beginner",
    gradeBucket: "lower-primary",
    prompt: "Which one can roll?",
    options: ["Box", "Ball", "Book", "Plate"],
    answer: "Ball",
    explanation: "A ball has a round shape that allows it to roll easily.",
  },
  {
    id: "phy-lp-beg-10",
    subjectId: "physics",
    difficulty: "Beginner",
    gradeBucket: "lower-primary",
    prompt: "What happens to a shadow when the light is blocked?",
    options: ["It appears", "It sings", "It freezes", "It grows leaves"],
    answer: "It appears",
    explanation: "A shadow forms when light is blocked.",
  },
  {
    id: "phy-up-beg-1",
    subjectId: "physics",
    difficulty: "Beginner",
    gradeBucket: "upper-primary",
    prompt: "Which force pulls objects toward the Earth?",
    options: ["Friction", "Magnetism", "Gravity", "Electricity"],
    answer: "Gravity",
    explanation: "Gravity is the force that pulls objects toward the Earth.",
  },
  {
    id: "phy-up-beg-2",
    subjectId: "physics",
    difficulty: "Beginner",
    gradeBucket: "upper-primary",
    prompt: "What is the main source of energy for Earth?",
    options: ["Moon", "Sun", "Windmill", "Battery"],
    answer: "Sun",
    explanation: "The sun provides most of the energy used on Earth.",
  },
  {
    id: "phy-up-beg-3",
    subjectId: "physics",
    difficulty: "Beginner",
    gradeBucket: "upper-primary",
    prompt: "Which material is a good conductor of electricity?",
    options: ["Rubber", "Plastic", "Copper", "Wood"],
    answer: "Copper",
    explanation: "Copper is a metal and a good conductor of electricity.",
  },
  {
    id: "phy-up-beg-4",
    subjectId: "physics",
    difficulty: "Beginner",
    gradeBucket: "upper-primary",
    prompt: "Which quantity is measured in newtons?",
    options: ["Mass", "Force", "Time", "Temperature"],
    answer: "Force",
    explanation: "Force is measured in newtons.",
  },
  {
    id: "phy-up-beg-5",
    subjectId: "physics",
    difficulty: "Beginner",
    gradeBucket: "upper-primary",
    prompt: "What happens to the speed of a moving object when friction increases?",
    options: ["It always doubles", "It decreases", "It disappears", "It becomes light"],
    answer: "It decreases",
    explanation: "Friction opposes motion and can slow an object down.",
  },
  {
    id: "phy-up-beg-6",
    subjectId: "physics",
    difficulty: "Beginner",
    gradeBucket: "upper-primary",
    prompt: "Which simple machine is used to lift water from a well in many villages?",
    options: ["Pulley", "Wheelbarrow", "Knife", "Cup"],
    answer: "Pulley",
    explanation: "A pulley helps lift loads more easily.",
  },
  {
    id: "phy-up-beg-7",
    subjectId: "physics",
    difficulty: "Beginner",
    gradeBucket: "upper-primary",
    prompt: "Which type of energy is stored in food?",
    options: ["Sound energy", "Chemical energy", "Light energy", "Nuclear energy"],
    answer: "Chemical energy",
    explanation: "Food stores chemical energy.",
  },
  {
    id: "phy-up-beg-8",
    subjectId: "physics",
    difficulty: "Beginner",
    gradeBucket: "upper-primary",
    prompt: "What kind of image is formed on a cinema screen?",
    options: ["Virtual image", "Real image", "Shadow image", "Magnetic image"],
    answer: "Real image",
    explanation: "A projector forms a real image on the screen.",
  },
  {
    id: "phy-up-beg-9",
    subjectId: "physics",
    difficulty: "Beginner",
    gradeBucket: "upper-primary",
    prompt: "Which instrument measures temperature?",
    options: ["Thermometer", "Barometer", "Voltmeter", "Ruler"],
    answer: "Thermometer",
    explanation: "A thermometer is used to measure temperature.",
  },
  {
    id: "phy-up-beg-10",
    subjectId: "physics",
    difficulty: "Beginner",
    gradeBucket: "upper-primary",
    prompt: "Why is it easier to ride a bicycle on a smooth road than on rough ground?",
    options: ["Less friction", "More gravity", "More mass", "Less light"],
    answer: "Less friction",
    explanation: "A smooth road provides less friction and resistance.",
  },
  {
    id: "chem-lp-beg-1",
    subjectId: "chemistry",
    difficulty: "Beginner",
    gradeBucket: "lower-primary",
    prompt: "Which of these is a liquid?",
    options: ["Stone", "Milk", "Book", "Chalk"],
    answer: "Milk",
    explanation: "Milk is a liquid because it can flow and take the shape of its container.",
  },
  {
    id: "chem-lp-beg-2",
    subjectId: "chemistry",
    difficulty: "Beginner",
    gradeBucket: "lower-primary",
    prompt: "Water can be found as ice, liquid water, and what else?",
    options: ["Wood", "Steam", "Sand", "Paper"],
    answer: "Steam",
    explanation: "Water can exist as solid ice, liquid water, and gaseous steam.",
  },
  {
    id: "chem-lp-beg-3",
    subjectId: "chemistry",
    difficulty: "Beginner",
    gradeBucket: "lower-primary",
    prompt: "Which of these can dissolve in water?",
    options: ["Sugar", "Stone", "Metal spoon", "Leaf"],
    answer: "Sugar",
    explanation: "Sugar dissolves in water to form a solution.",
  },
  {
    id: "chem-lp-beg-4",
    subjectId: "chemistry",
    difficulty: "Beginner",
    gradeBucket: "lower-primary",
    prompt: "Which one is a gas?",
    options: ["Air", "Water", "Bottle", "Soap"],
    answer: "Air",
    explanation: "Air is a mixture of gases.",
  },
  {
    id: "chem-lp-beg-5",
    subjectId: "chemistry",
    difficulty: "Beginner",
    gradeBucket: "lower-primary",
    prompt: "What happens when ice is warmed?",
    options: ["It melts", "It grows", "It turns to metal", "It becomes paper"],
    answer: "It melts",
    explanation: "Ice melts into liquid water when it is warmed.",
  },
  {
    id: "chem-lp-beg-6",
    subjectId: "chemistry",
    difficulty: "Beginner",
    gradeBucket: "lower-primary",
    prompt: "Which of these is used to clean dirty hands?",
    options: ["Soap", "Sand", "Stone", "Dust"],
    answer: "Soap",
    explanation: "Soap helps remove dirt and grease.",
  },
  {
    id: "chem-lp-beg-7",
    subjectId: "chemistry",
    difficulty: "Beginner",
    gradeBucket: "lower-primary",
    prompt: "Which material is transparent?",
    options: ["Wood", "Clear glass", "Cardboard", "Cloth"],
    answer: "Clear glass",
    explanation: "Transparent materials allow light to pass through them clearly.",
  },
  {
    id: "chem-lp-beg-8",
    subjectId: "chemistry",
    difficulty: "Beginner",
    gradeBucket: "lower-primary",
    prompt: "Which of these is a solid?",
    options: ["Juice", "Air", "Ice block", "Smoke"],
    answer: "Ice block",
    explanation: "An ice block is a solid state of water.",
  },
  {
    id: "chem-lp-beg-9",
    subjectId: "chemistry",
    difficulty: "Beginner",
    gradeBucket: "lower-primary",
    prompt: "What do we call water mixed with salt?",
    options: ["Stone", "Salt solution", "Metal", "Steam"],
    answer: "Salt solution",
    explanation: "When salt dissolves in water, it forms a salt solution.",
  },
  {
    id: "chem-lp-beg-10",
    subjectId: "chemistry",
    difficulty: "Beginner",
    gradeBucket: "lower-primary",
    prompt: "Which of these changes shape easily?",
    options: ["Liquid", "Rock", "Brick", "Table"],
    answer: "Liquid",
    explanation: "Liquids take the shape of their container.",
  },
  {
    id: "chem-up-beg-1",
    subjectId: "chemistry",
    difficulty: "Beginner",
    gradeBucket: "upper-primary",
    prompt: "Which process changes liquid water to water vapour?",
    options: ["Melting", "Evaporation", "Freezing", "Condensation"],
    answer: "Evaporation",
    explanation: "Evaporation changes a liquid into a gas.",
  },
  {
    id: "chem-up-beg-2",
    subjectId: "chemistry",
    difficulty: "Beginner",
    gradeBucket: "upper-primary",
    prompt: "Which of these is a mixture?",
    options: ["Salt water", "Pure gold", "Oxygen", "Iron nail"],
    answer: "Salt water",
    explanation: "Salt water is made from salt and water mixed together.",
  },
  {
    id: "chem-up-beg-3",
    subjectId: "chemistry",
    difficulty: "Beginner",
    gradeBucket: "upper-primary",
    prompt: "Which method can separate sand from water?",
    options: ["Filtering", "Freezing", "Burning", "Magnetizing"],
    answer: "Filtering",
    explanation: "Filtering separates an insoluble solid from a liquid.",
  },
  {
    id: "chem-up-beg-4",
    subjectId: "chemistry",
    difficulty: "Beginner",
    gradeBucket: "upper-primary",
    prompt: "What is the pH of a neutral solution?",
    options: ["0", "3", "7", "14"],
    answer: "7",
    explanation: "A neutral solution has a pH of 7.",
  },
  {
    id: "chem-up-beg-5",
    subjectId: "chemistry",
    difficulty: "Beginner",
    gradeBucket: "upper-primary",
    prompt: "Which gas do plants use for photosynthesis?",
    options: ["Oxygen", "Nitrogen", "Carbon dioxide", "Helium"],
    answer: "Carbon dioxide",
    explanation: "Plants take in carbon dioxide during photosynthesis.",
  },
  {
    id: "chem-up-beg-6",
    subjectId: "chemistry",
    difficulty: "Beginner",
    gradeBucket: "upper-primary",
    prompt: "Which of these is an example of rusting?",
    options: ["Ice melting", "Iron reacting with air and water", "Sugar dissolving", "Water boiling"],
    answer: "Iron reacting with air and water",
    explanation: "Rusting happens when iron reacts with oxygen and water.",
  },
  {
    id: "chem-up-beg-7",
    subjectId: "chemistry",
    difficulty: "Beginner",
    gradeBucket: "upper-primary",
    prompt: "What is the smallest unit of an element?",
    options: ["Cell", "Atom", "Organ", "Crystal"],
    answer: "Atom",
    explanation: "An atom is the smallest unit of an element.",
  },
  {
    id: "chem-up-beg-8",
    subjectId: "chemistry",
    difficulty: "Beginner",
    gradeBucket: "upper-primary",
    prompt: "Which of these is an acid found in citrus fruits?",
    options: ["Citric acid", "Soap", "Salt", "Chalk"],
    answer: "Citric acid",
    explanation: "Citrus fruits such as oranges contain citric acid.",
  },
  {
    id: "chem-up-beg-9",
    subjectId: "chemistry",
    difficulty: "Beginner",
    gradeBucket: "upper-primary",
    prompt: "What do we call a substance that speeds up digestion of food in the body?",
    options: ["Enzyme", "Rock", "Battery", "Sand"],
    answer: "Enzyme",
    explanation: "Enzymes help speed up chemical reactions in living things.",
  },
  {
    id: "chem-up-beg-10",
    subjectId: "chemistry",
    difficulty: "Beginner",
    gradeBucket: "upper-primary",
    prompt: "Which state of matter has a fixed shape and fixed volume?",
    options: ["Gas", "Liquid", "Solid", "Steam"],
    answer: "Solid",
    explanation: "Solids have a fixed shape and fixed volume.",
  },
  {
    id: "bio-lp-beg-1",
    subjectId: "biology",
    difficulty: "Beginner",
    gradeBucket: "lower-primary",
    prompt: "Which part of the body is used for seeing?",
    options: ["Ears", "Eyes", "Nose", "Hands"],
    answer: "Eyes",
    explanation: "We use our eyes to see.",
  },
  {
    id: "bio-lp-beg-2",
    subjectId: "biology",
    difficulty: "Beginner",
    gradeBucket: "lower-primary",
    prompt: "Which of these is a living thing?",
    options: ["Stone", "Goat", "Chair", "Cup"],
    answer: "Goat",
    explanation: "A goat is a living thing because it grows, feeds, and reproduces.",
  },
  {
    id: "bio-lp-beg-3",
    subjectId: "biology",
    difficulty: "Beginner",
    gradeBucket: "lower-primary",
    prompt: "Which part of a plant takes in water from the soil?",
    options: ["Leaf", "Flower", "Root", "Fruit"],
    answer: "Root",
    explanation: "Roots absorb water and minerals from the soil.",
  },
  {
    id: "bio-lp-beg-4",
    subjectId: "biology",
    difficulty: "Beginner",
    gradeBucket: "lower-primary",
    prompt: "Which animal gives us milk?",
    options: ["Cow", "Lizard", "Hen", "Fish"],
    answer: "Cow",
    explanation: "Cows are common animals that produce milk.",
  },
  {
    id: "bio-lp-beg-5",
    subjectId: "biology",
    difficulty: "Beginner",
    gradeBucket: "lower-primary",
    prompt: "Which part of the body helps us walk?",
    options: ["Legs", "Teeth", "Hair", "Nails"],
    answer: "Legs",
    explanation: "We use our legs for walking and running.",
  },
  {
    id: "bio-lp-beg-6",
    subjectId: "biology",
    difficulty: "Beginner",
    gradeBucket: "lower-primary",
    prompt: "What do plants need to make food?",
    options: ["Light", "Plastic", "Sandpaper", "Nails"],
    answer: "Light",
    explanation: "Plants need light for photosynthesis.",
  },
  {
    id: "bio-lp-beg-7",
    subjectId: "biology",
    difficulty: "Beginner",
    gradeBucket: "lower-primary",
    prompt: "Which body part is used for breathing?",
    options: ["Lungs", "Bones", "Eyes", "Feet"],
    answer: "Lungs",
    explanation: "The lungs help us breathe.",
  },
  {
    id: "bio-lp-beg-8",
    subjectId: "biology",
    difficulty: "Beginner",
    gradeBucket: "lower-primary",
    prompt: "Which of these is a bird?",
    options: ["Cat", "Hen", "Goat", "Dog"],
    answer: "Hen",
    explanation: "A hen is a bird.",
  },
  {
    id: "bio-lp-beg-9",
    subjectId: "biology",
    difficulty: "Beginner",
    gradeBucket: "lower-primary",
    prompt: "Which part of a plant is usually green and makes food?",
    options: ["Leaf", "Root", "Stem", "Seed"],
    answer: "Leaf",
    explanation: "Leaves contain chlorophyll and help plants make food.",
  },
  {
    id: "bio-lp-beg-10",
    subjectId: "biology",
    difficulty: "Beginner",
    gradeBucket: "lower-primary",
    prompt: "Which of these helps babies grow strong?",
    options: ["Food", "Stones", "Sand", "Smoke"],
    answer: "Food",
    explanation: "Food gives the body energy and helps it grow.",
  },
  {
    id: "bio-up-beg-1",
    subjectId: "biology",
    difficulty: "Beginner",
    gradeBucket: "upper-primary",
    prompt: "Which organ pumps blood around the body?",
    options: ["Liver", "Heart", "Lungs", "Stomach"],
    answer: "Heart",
    explanation: "The heart pumps blood through the circulatory system.",
  },
  {
    id: "bio-up-beg-2",
    subjectId: "biology",
    difficulty: "Beginner",
    gradeBucket: "upper-primary",
    prompt: "What is the basic unit of life?",
    options: ["Leaf", "Cell", "Bone", "Blood vessel"],
    answer: "Cell",
    explanation: "The cell is the basic unit of life.",
  },
  {
    id: "bio-up-beg-3",
    subjectId: "biology",
    difficulty: "Beginner",
    gradeBucket: "upper-primary",
    prompt: "Which process do plants use to make food?",
    options: ["Respiration", "Photosynthesis", "Digestion", "Excretion"],
    answer: "Photosynthesis",
    explanation: "Plants make food by photosynthesis.",
  },
  {
    id: "bio-up-beg-4",
    subjectId: "biology",
    difficulty: "Beginner",
    gradeBucket: "upper-primary",
    prompt: "Which nutrient helps the body build and repair tissues?",
    options: ["Protein", "Water", "Salt", "Air"],
    answer: "Protein",
    explanation: "Protein helps in growth and repair of body tissues.",
  },
  {
    id: "bio-up-beg-5",
    subjectId: "biology",
    difficulty: "Beginner",
    gradeBucket: "upper-primary",
    prompt: "Which part of the digestive system stores food for a short time after swallowing?",
    options: ["Brain", "Stomach", "Lungs", "Skin"],
    answer: "Stomach",
    explanation: "The stomach stores and digests food.",
  },
  {
    id: "bio-up-beg-6",
    subjectId: "biology",
    difficulty: "Beginner",
    gradeBucket: "upper-primary",
    prompt: "Animals that eat only plants are called what?",
    options: ["Carnivores", "Omnivores", "Herbivores", "Predators"],
    answer: "Herbivores",
    explanation: "Herbivores feed on plants.",
  },
  {
    id: "bio-up-beg-7",
    subjectId: "biology",
    difficulty: "Beginner",
    gradeBucket: "upper-primary",
    prompt: "Which system helps the body get rid of waste products?",
    options: ["Reproductive system", "Excretory system", "Skeletal system", "Nervous system"],
    answer: "Excretory system",
    explanation: "The excretory system removes waste from the body.",
  },
  {
    id: "bio-up-beg-8",
    subjectId: "biology",
    difficulty: "Beginner",
    gradeBucket: "upper-primary",
    prompt: "Which part of a flower develops into a fruit after fertilization?",
    options: ["Petal", "Ovary", "Leaf", "Stem"],
    answer: "Ovary",
    explanation: "The ovary develops into the fruit after fertilization.",
  },
  {
    id: "bio-up-beg-9",
    subjectId: "biology",
    difficulty: "Beginner",
    gradeBucket: "upper-primary",
    prompt: "Which gas do humans breathe in for respiration?",
    options: ["Carbon dioxide", "Oxygen", "Hydrogen", "Chlorine"],
    answer: "Oxygen",
    explanation: "Humans breathe in oxygen for respiration.",
  },
  {
    id: "bio-up-beg-10",
    subjectId: "biology",
    difficulty: "Beginner",
    gradeBucket: "upper-primary",
    prompt: "A group of organisms living together with their environment is called what?",
    options: ["Cell", "Ecosystem", "Tissue", "Organ"],
    answer: "Ecosystem",
    explanation: "An ecosystem includes living things and their environment.",
  },
  {
    id: "comp-lp-beg-1",
    subjectId: "computer",
    difficulty: "Beginner",
    gradeBucket: "lower-primary",
    prompt: "Which device shows pictures and words from a computer?",
    options: ["Monitor", "Keyboard", "Mouse", "Speaker"],
    answer: "Monitor",
    explanation: "The monitor displays information on the screen.",
  },
  {
    id: "comp-lp-beg-2",
    subjectId: "computer",
    difficulty: "Beginner",
    gradeBucket: "lower-primary",
    prompt: "Which part of the computer do you type on?",
    options: ["Monitor", "Mouse", "Keyboard", "Printer"],
    answer: "Keyboard",
    explanation: "The keyboard is used for typing.",
  },
  {
    id: "comp-lp-beg-3",
    subjectId: "computer",
    difficulty: "Beginner",
    gradeBucket: "lower-primary",
    prompt: "Which device helps move the pointer on the screen?",
    options: ["Cup", "Mouse", "Book", "Fan"],
    answer: "Mouse",
    explanation: "A mouse is used to control the pointer.",
  },
  {
    id: "comp-lp-beg-4",
    subjectId: "computer",
    difficulty: "Beginner",
    gradeBucket: "lower-primary",
    prompt: "Which device prints your work on paper?",
    options: ["Printer", "Scanner", "Speaker", "Battery"],
    answer: "Printer",
    explanation: "A printer produces a hard copy on paper.",
  },
  {
    id: "comp-lp-beg-5",
    subjectId: "computer",
    difficulty: "Beginner",
    gradeBucket: "lower-primary",
    prompt: "What should you do before touching a computer with dirty hands?",
    options: ["Run away", "Wash your hands", "Pour water on it", "Kick the chair"],
    answer: "Wash your hands",
    explanation: "Keeping hands clean helps protect the computer.",
  },
  {
    id: "comp-lp-beg-6",
    subjectId: "computer",
    difficulty: "Beginner",
    gradeBucket: "lower-primary",
    prompt: "Which of these is used to listen to sound from a computer?",
    options: ["Speaker", "Table", "Keyboard", "Cable"],
    answer: "Speaker",
    explanation: "Speakers play sound.",
  },
  {
    id: "comp-lp-beg-7",
    subjectId: "computer",
    difficulty: "Beginner",
    gradeBucket: "lower-primary",
    prompt: "Which one is an input device?",
    options: ["Monitor", "Keyboard", "Screen", "Printer"],
    answer: "Keyboard",
    explanation: "A keyboard sends data into the computer, so it is an input device.",
  },
  {
    id: "comp-lp-beg-8",
    subjectId: "computer",
    difficulty: "Beginner",
    gradeBucket: "lower-primary",
    prompt: "What should you click to open a program on a touchscreen?",
    options: ["The sky", "The icon", "The floor", "The table"],
    answer: "The icon",
    explanation: "You tap an icon to open an app or program.",
  },
  {
    id: "comp-lp-beg-9",
    subjectId: "computer",
    difficulty: "Beginner",
    gradeBucket: "lower-primary",
    prompt: "Which of these stores your files?",
    options: ["Memory/storage", "Chair", "Cup", "Window"],
    answer: "Memory/storage",
    explanation: "A computer stores files in memory or storage devices.",
  },
  {
    id: "comp-lp-beg-10",
    subjectId: "computer",
    difficulty: "Beginner",
    gradeBucket: "lower-primary",
    prompt: "What does a computer need to work?",
    options: ["Electric power", "Sand", "Soap", "Rain"],
    answer: "Electric power",
    explanation: "A computer needs power from electricity or a battery.",
  },
  {
    id: "comp-up-beg-1",
    subjectId: "computer",
    difficulty: "Beginner",
    gradeBucket: "upper-primary",
    prompt: "Which part of a computer is often called the brain of the computer?",
    options: ["Monitor", "CPU", "Mouse", "Printer"],
    answer: "CPU",
    explanation: "The CPU processes instructions and controls many computer operations.",
  },
  {
    id: "comp-up-beg-2",
    subjectId: "computer",
    difficulty: "Beginner",
    gradeBucket: "upper-primary",
    prompt: "What does URL stand for?",
    options: ["Uniform Resource Locator", "Universal Reading List", "User Record Login", "Unique Route Link"],
    answer: "Uniform Resource Locator",
    explanation: "URL stands for Uniform Resource Locator.",
  },
  {
    id: "comp-up-beg-3",
    subjectId: "computer",
    difficulty: "Beginner",
    gradeBucket: "upper-primary",
    prompt: "Which of these is a web browser?",
    options: ["Chrome", "Word", "Excel", "Paint"],
    answer: "Chrome",
    explanation: "Chrome is used to browse websites on the internet.",
  },
  {
    id: "comp-up-beg-4",
    subjectId: "computer",
    difficulty: "Beginner",
    gradeBucket: "upper-primary",
    prompt: "Which storage unit is larger?",
    options: ["Byte", "Kilobyte", "Megabyte", "Bit"],
    answer: "Megabyte",
    explanation: "A megabyte is larger than a kilobyte or a byte.",
  },
  {
    id: "comp-up-beg-5",
    subjectId: "computer",
    difficulty: "Beginner",
    gradeBucket: "upper-primary",
    prompt: "What should you use to keep your online accounts safe?",
    options: ["A strong password", "Your name only", "No password", "A blank screen"],
    answer: "A strong password",
    explanation: "A strong password helps protect your accounts.",
  },
  {
    id: "comp-up-beg-6",
    subjectId: "computer",
    difficulty: "Beginner",
    gradeBucket: "upper-primary",
    prompt: "Which one is an operating system?",
    options: ["Windows", "Keyboard", "Speaker", "USB cable"],
    answer: "Windows",
    explanation: "Windows is an operating system.",
  },
  {
    id: "comp-up-beg-7",
    subjectId: "computer",
    difficulty: "Beginner",
    gradeBucket: "upper-primary",
    prompt: "What is the internet mainly used for?",
    options: ["Connecting computers and sharing information", "Cooking food", "Measuring temperature", "Growing plants"],
    answer: "Connecting computers and sharing information",
    explanation: "The internet connects devices and allows information sharing.",
  },
  {
    id: "comp-up-beg-8",
    subjectId: "computer",
    difficulty: "Beginner",
    gradeBucket: "upper-primary",
    prompt: "Which shortcut is commonly used to copy selected text?",
    options: ["Ctrl + C", "Ctrl + P", "Ctrl + Z", "Ctrl + S"],
    answer: "Ctrl + C",
    explanation: "Ctrl + C is the common shortcut for copy.",
  },
  {
    id: "comp-up-beg-9",
    subjectId: "computer",
    difficulty: "Beginner",
    gradeBucket: "upper-primary",
    prompt: "Which device can be used to store files and move them between computers?",
    options: ["Flash drive", "Monitor", "Mouse pad", "Paper clip"],
    answer: "Flash drive",
    explanation: "A flash drive is a portable storage device.",
  },
  {
    id: "comp-up-beg-10",
    subjectId: "computer",
    difficulty: "Beginner",
    gradeBucket: "upper-primary",
    prompt: "What does it mean to upload a file?",
    options: ["Send it from your device to the internet or another system", "Delete it forever", "Print it on paper", "Rename the keyboard"],
    answer: "Send it from your device to the internet or another system",
    explanation: "Uploading means sending a file from your device to a remote system.",
  },
];

function toGradeBucket(grade: string): GradeBucket {
  const gradeNumber = Number(grade.replace(/[^\d]/g, ""));
  if (Number.isFinite(gradeNumber) && gradeNumber >= 4) {
    return "upper-primary";
  }

  return "lower-primary";
}

function rotate<T>(items: T[], offset: number) {
  if (items.length === 0) {
    return items;
  }

  const start = offset % items.length;
  return [...items.slice(start), ...items.slice(0, start)];
}

export function getLocalQuestions(request: QuestionRequest): Question[] {
  const gradeBucket = toGradeBucket(request.grade);

  const exact = bank.filter(
    (question) =>
      question.subjectId === request.subject.id &&
      question.difficulty === request.difficulty &&
      question.gradeBucket === gradeBucket
  );

  const subjectFallback = bank.filter(
    (question) => question.subjectId === request.subject.id && question.gradeBucket === gradeBucket
  );

  const difficultyFallback = bank.filter(
    (question) => question.subjectId === request.subject.id && question.difficulty === request.difficulty
  );

  const pool = exact.length >= request.questionCount
    ? exact
    : subjectFallback.length >= request.questionCount
      ? subjectFallback
      : difficultyFallback;

  if (pool.length === 0) {
    return [];
  }

  const rotated = rotate(pool, Math.max(request.level - 1, 0) * request.questionCount);
  return rotated.slice(0, Math.min(request.questionCount, rotated.length)).map(({ subjectId, difficulty, gradeBucket: bucket, ...question }) => question);
}
